(define simplify
  (lambda (expr)
    (cond
     ((null? expr) '())
     ((or (symbol? expr) (number? expr)) expr)
     (else
      (let ((expr-len (length expr)))
	(cond ((= 2 expr-len)
	       (let* ((op (car expr))
		      (n (car (cdr expr)))
		      (dec (equal? op 'dec))
		      (inc (equal? op 'inc)))
		 (if (number? n)
		     (cond (dec (- n 1))
			   (inc (+ n 1))
			   (else (error "Uknown operator" op)))
		     expr)))
	      ((= 3 expr-len)
	       (let* ((operand1 (simplify (first expr)))
		      (operator (second expr))
		      (operand2 (simplify (third expr)))
		      (plus (equal? operator '+))
		      (minus (equal? operator '-))
		      (mult (equal? operator '*))
		      (div (equal? operator '/))
		      (exp (equal? operator '**))
		      (o1-zero (equal? operand1 0))
		      (o2-zero (equal? operand2 0))
		      (o1-one (equal? operand1 1))
		      (o2-one (equal? operand2 1))
		      (o1-is-lst (list? operand1))
		      (o2-is-lst (list? operand2))
		      (o1-is-num (number? operand1))
		      (o2-is-num (number? operand2))
		      (o1-is-sym (symbol? operand1))
		      (o2-is-sym (symbol? operand2))
		      (s1-is-lst (list? operand1))
		      (s2-is-lst (list? operand2))
		      (lst (list operand1 operator operand2)))
		 (cond ((and plus o1-zero) operand2)
		       ((and plus o2-zero) operand1)
		       ((and mult (or o1-zero o2-zero)) 0)
		       ((and mult o1-one) operand2)
		       ((and mult o2-one) operand1)
		       ((and div o2-one) operand1)
		       ((and minus o2-zero) operand1)
		       ((and minus (equal? operand1 operand2)) 0)
		       ((and exp o2-zero) 1)
		       ((and exp o2-one) operand1)
		       ((and exp o1-one) 1)
		       ((or (and o1-is-sym o2-is-num)
			    (and o1-is-num o2-is-sym)
			    (or s1-is-lst s2-is-lst)
			    (and o1-is-sym o2-is-sym)
			    (and o1-is-num o2-is-num)) lst)
		       (else (simplify lst)))))
	      (else (error "Invalid expression"))))))))
